title: Portafolio Grupo A
baseurl: ""
url: "https://PortafolioGrupoA.github.io"
exclude:
  - protected-content/  # Excluir carpeta protegida del build
  - login.html
  - package.json
  - node_modules
